feat(framework): add hook for returning users screen size
mediatool/northlight pull request #108
Opened 2023-09-11 07:37 UTC by JonathanNeville

add hook that returns a string value corresponding to the screen size of the user

2023-09-11 12:48 UTC, TautvydasGec approved these changes
this looks good to me but i would love for northlight ppl say if this what we want

2023-09-12 09:33 UTC, SebCodesTheWeb requested changes

2023-09-12 09:33 UTC, SebCodesTheWeb commented on framework/test/unit/hooks/use-screen-size-test.ts
> +  })
This test prob not needed, the dependency as well. If you want to keep the test then atleast move the dependency as a dev dependency

2023-09-12 09:33 UTC, SebCodesTheWeb commented on framework/lib/hooks/use-screen-size/index.ts
> +}
Use lg, md, sm instaed

2023-09-12 13:48 UTC, SebCodesTheWeb approved these changes

2023-09-12 13:48 UTC, merged