fix(framework): added polyfill for window.matchMedia
mediatool/northlight pull request #125
Opened 2023-09-13 15:13 UTC by SebCodesTheWeb

In chakra-react-select v.4.5.0 @chakra-ui/media-query was added as a dependency. This uses window.matchMedia api which is not defined in testing environment. This polyfills should effectively stub it in the library itself and fix the issues in the tests that use Northlight

closed DEV-9240
closed DEV-9242

2023-09-15 10:39 UTC, TautvydasGec approved these changes

2023-09-15 10:40 UTC, TautvydasGec commented
@SebCodesTheWeb did you test with the tests skipped in domains?

2023-09-15 10:44 UTC, orestisrodriguez requested changes
matchMedia has been supported on browsers for more than 10 years, so I think this is the wrong way to fix the issue. the library doesn't need a polyfill itself, but rather the test runner's fake DOM (jsdom) environment does.

2023-09-15 12:21 UTC, TautvydasGec commented
Jest official statement is this https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom i guess you can assign that window object only in test runner

2023-09-18 10:55 UTC, SebCodesTheWeb commented
Moved to : https://github.com/mediatool/mediatool/pull/13268

2023-09-18 10:55 UTC, closed without merging