fix(framework): Select dropdown direction if cant fit in modal
mediatool/northlight pull request #160
Opened 2023-10-23 14:36 UTC by SebCodesTheWeb

This will make it so the select dropdown will be displayed on top of the select input in case there is not enough space at the bottom. This applies for all container, including modal.

closed: DEV-9724

2023-10-24 07:54 UTC, ilija- approved these changes

2023-10-24 07:59 UTC, magnusohlin requested changes
https://github.com/mediatool/northlight/assets/521837/25b379f5-4579-4c90-aa56-6e047322700d

Not exactly sure how this should work? This is when it overflows the window. Still opens below but scrolls the window. Also have you considered keyboard interactions when the select opens above the field, should the user type up-arrow then instead?

2023-10-25 11:28 UTC, SebCodesTheWeb commented
https://github.com/mediatool/northlight/assets/90923099/d7848752-b7ac-453b-98c9-dd28c7399818

@magnusohlin I have made it so that the dropdown will be displayed on top of the select input in case it does not fit into _either_ its parent div, or the viewport window. I also added a minDropdownHeightPx prop

2023-10-25 11:32 UTC, magnusohlin approved these changes

2023-10-25 11:36 UTC, merged