feat(docs): add changelog-news page
mediatool/northlight pull request #171
Opened 2023-11-02 11:55 UTC by SebCodesTheWeb

2023-11-06 09:33 UTC, ilija- requested changes

2023-11-06 09:33 UTC, ilija- commented on docs/src/docs/app.tsx
> +    <Card w="70%" mx="auto" bgColor="bg.layer" borderRadius="md" maxH="4xl" overflowY="scroll">
`<Card w="70%" mx="auto" bgColor="bg.layer" borderRadius="md" maxH="4xl" overflowY="scroll">`

Please put the stylings in a new row for better code readability. 

```
<Card 
w="70%" 
mx="auto" 
bgColor="bg.layer"
borderRadius="md" 
maxH="4xl" 
overflowY="scroll"
>
```

2023-11-06 09:33 UTC, ilija- commented on docs/src/docs/app.tsx
> +        <Box bgColor="bg.overlayer" borderRadius="md" p="8">
Same here ( if there are 3+ stylings )

```
<Box
bgColor="bg.overlayer"
borderRadius="md" 
p="8"
>
```

2023-11-08 08:19 UTC, magnusohlin approved these changes

2023-11-08 08:27 UTC, ilija- approved these changes

2023-11-08 08:28 UTC, merged