feat(framework): addAlpha util
mediatool/northlight pull request #33
Opened 2023-02-24 17:34 UTC by SebCodesTheWeb

2023-02-24 17:42 UTC, ilija- approved these changes

2023-02-24 17:56 UTC, olchyk98 approved these changes

2023-02-24 17:56 UTC, olchyk98 commented on framework/lib/utils/addAlpha/index.ts
> +import { useToken } from '@chakra-ui/system'
Could you write a unit test for `addAlpha`?

2023-02-24 17:56 UTC, olchyk98 requested changes
approved by mistake

2023-02-27 07:21 UTC, magnusohlin approved these changes

2023-02-27 10:17 UTC, olchyk98 approved these changes

2023-02-27 10:17 UTC, merged