fix(northlight/landing): Giants block causing page size issues
mediatool/northlight pull request #34
Opened 2023-02-24 18:12 UTC by ilija-

This fix is resolving the giants block going out of the viewport issue, and causing the appearance of a horizontal scroll on the /components page after paolo's card was added.

2023-02-27 07:23 UTC, magnusohlin requested changes
Just some linting errors

2023-02-27 07:23 UTC, magnusohlin commented on framework/sandbox/docs/app.tsx
> +          <Card maxW="xs" boxShadow="none" borderColor="white" bgColor="transparent">
Indent this row

2023-02-27 07:23 UTC, magnusohlin commented on framework/sandbox/docs/app.tsx
> +
Remove blank row

2023-02-27 17:05 UTC, SebCodesTheWeb commented
This is not how you want to name your commits, always follow conventional commits: https://www.conventionalcommits.org/en/v1.0.0/. And if a fix was needed, like linting, you want to amend it, or squash it to the previous commit, basically combining them. You can ask me if you need help with this.

2023-02-28 08:07 UTC, magnusohlin commented
https://user-images.githubusercontent.com/521837/221791480-5810f55c-d564-4451-a9fa-54534419e6ad.mov

@ilija- I think you have received the branch-rebase script from me, I did a little video for you on how to squash your commits

2023-02-28 08:08 UTC, magnusohlin commented
There is a slight error in my video above, the top commit should be fix(framework): bla bla

2023-02-28 13:46 UTC, magnusohlin approved these changes

2023-03-01 08:47 UTC, merged