chore(northlight): new labelSize prop for SwitchField
mediatool/northlight pull request #85
Opened 2023-07-13 13:00 UTC by ilija-

- labelSize added
- Flex / Alignment fixes

closes: DEV-8557

2023-07-13 13:07 UTC, unganemo commented on framework/lib/components/switch/switch-field.tsx
> +  labelPosition = 'right',
maybe change to labelPlacement to have more continuity? (iconPlacement in FlipButton)

2023-07-13 13:18 UTC, ilija- commented on framework/lib/components/switch/switch-field.tsx
> +          { label && <Label htmlFor={ name } sx={ { fontWeight: 'normal' } } size={ labelSize }>{ label }</Label> }
it is not.

2023-07-13 14:27 UTC, TautvydasGec commented
Squash all commits

2023-07-13 14:37 UTC, unganemo requested changes

2023-07-13 14:37 UTC, unganemo commented on framework/lib/components/switch/switch-field.tsx
> +          { <Label htmlFor={ name } sx={ { fontWeight: 'normal' } } size={ labelSize }>{ label }</Label> }
remove curly braces here, that's what's making the test fail

2023-07-14 07:39 UTC, TautvydasGec commented
To squash all commits do this:
1. `git config --global core.editor "code --wait"` (only need this once) next time you do this you dont need this part
2. go to master and do `git pull`
3. go to your branch and do `git rebase -i master`
4. VS code window will open up. click on top right corner to enable oldest first
5. on the first line select pick and on all the other lines squash
6. cmd+Enter
7. write your commit message (This will have all your commit messages smushed together in one file)
8. exit window.
9. `git push --force`
10. profit

2023-07-31 08:10 UTC, unganemo requested changes
All flip button changes should not be in this PR. Two weeks late but hey better late than never

2023-07-31 12:09 UTC, ilija- commented
> All flip button changes should not be in this PR. Two weeks late but hey better late than never

@unganemo 

This happened when I squashed the commit along with your commits, somehow.
There is also an update on the CheckboxField that you might be interested in, which is already merged. The same new props as this one.

2023-07-31 13:21 UTC, orestisrodriguez commented
@unganemo @ilija- this seems against the composability that northlight and chakra has. the icon imo should be a children and not part of the flip button itself, and you can pass whatever directional property to it?

```
<FlipButtonGroup>
  <FlipButton flexDirection="row">
    <Icon ... />
    <Text>...</Text>
  </FlipButton>
</FlipButtonGroup>
```

2023-10-24 09:18 UTC, unganemo approved these changes

2023-10-24 09:26 UTC, merged